# Generated by Django 2.1.5 on 2019-02-28 01:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concentrado',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='concentrado',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='concentrado',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Finca'),
        ),
        migrations.AddField(
            model_name='concentrado',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='concentrado',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
