# Generated by Django 2.1.5 on 2019-02-28 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20190227_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradebultos',
            name='precio_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concentrado',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compradebultos',
            name='responsable',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concentrado',
            name='finca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro.Finca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concentrado',
            name='proteina',
            field=models.PositiveSmallIntegerField(verbose_name='Proteina %'),
        ),
        migrations.AlterField(
            model_name='concentrado',
            name='responsable',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concentrado',
            name='total_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
