# Generated by Django 2.1.5 on 2019-03-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20190228_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentrado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
