# Generated by Django 2.1.5 on 2019-03-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20190321_0013'),
        ('inventario', '0004_auto_20190302_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradebultos',
            name='finca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro.Finca'),
            preserve_default=False,
        ),
    ]
