# Generated by Django 2.1.1 on 2018-10-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20181025_2338'),
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Finca',
        ),
    ]
