# Generated by Django 2.1.2 on 2018-11-17 06:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0015_auto_20181117_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='Calidad_agua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxigeno', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Oxígeno')),
                ('temperatura', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(100)], verbose_name='Temperatura')),
                ('dureza', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dureza')),
                ('ph', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH')),
                ('amonio', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('nitritos', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('nitratos', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('co2', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('estanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Estanque')),
            ],
        ),
        migrations.CreateModel(
            name='CompraBultos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Concentrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proteina', models.PositiveSmallIntegerField()),
                ('kilos', models.PositiveSmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Muestreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla_promedio_cm', models.PositiveSmallIntegerField()),
                ('peso_promedio_gr', models.PositiveSmallIntegerField()),
                ('peces_muertos', models.PositiveSmallIntegerField()),
                ('ganancia_diaria_peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('factor_de_conversion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('biomasa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ajuste_dieta', models.PositiveSmallIntegerField()),
                ('observaciones', models.TextField()),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='Racion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_gr', models.PositiveSmallIntegerField()),
                ('tipo_concentrado', models.CharField(max_length=100)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('alimentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Alimentacion')),
            ],
        ),
        migrations.AddField(
            model_name='comprabultos',
            name='concentrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Concentrado'),
        ),
    ]
