# Generated by Django 2.1.5 on 2019-02-14 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muestreo',
            old_name='porcentaje_aj',
            new_name='valor_ajuste_tabla',
        ),
        migrations.AddField(
            model_name='muestreo',
            name='Factor_conversion_alimenticia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='fca _:1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muestreo',
            name='biomasa',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Biomasa kg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rangos_calidad_agua',
            name='max_co2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rangos_calidad_agua',
            name='min_co2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calidad_agua',
            name='dureza',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dureza mg/l'),
        ),
    ]
