# Generated by Django 2.1.2 on 2018-11-29 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompraBultos',
            new_name='CompradeBultos',
        ),
    ]
