# Generated by Django 2.1.5 on 2019-02-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20190213_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestreo',
            name='biomasa',
        ),
    ]
