# Generated by Django 2.1.2 on 2018-12-01 05:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_cultivo_fecha_cosecha'),
        ('control', '0002_auto_20181129_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peces_muertos', models.PositiveSmallIntegerField(default=0)),
                ('responsable', models.CharField(max_length=100, verbose_name='auth.User')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Cultivo')),
            ],
        ),
        migrations.RemoveField(
            model_name='muestreo',
            name='peces_muertos',
        ),
        migrations.AlterField(
            model_name='calidad_agua',
            name='dureza',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='calidad_agua',
            name='ph',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='calidad_agua',
            name='temperatura',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
