# Generated by Django 2.1.5 on 2019-02-18 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20190218_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestreo',
            name='a_d',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ajuste dieta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muestreo',
            name='b',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='biomasa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muestreo',
            name='f_c_a',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='factor conversion alimenticia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muestreo',
            name='g_d_p',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ganancia diaria peso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='valor_ajuste_tabla',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
