# Generated by Django 2.1.5 on 2019-03-02 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20190218_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestreo',
            name='a_d',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ajuste dieta'),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='b',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='biomasa'),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='f_c_a',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='factor conversion alimenticia'),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='g_d_p',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ganancia diaria peso'),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='valor_ajuste_tabla',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
