# Generated by Django 2.1.5 on 2019-03-20 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20190302_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestreo',
            name='a_d',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ajuste dieta kg'),
        ),
    ]
