# Generated by Django 2.1.5 on 2019-03-21 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20190319_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racion',
            name='tipo_concentrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Concentrado'),
        ),
    ]
