# Generated by Django 2.1.5 on 2019-03-21 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20190320_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racion',
            name='cantidad_gr',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
