# Generated by Django 2.1.5 on 2019-03-21 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20190321_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangos_calidad_agua',
            name='max_oxigeno',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rangos_calidad_agua',
            name='min_oxigeno',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
