# Generated by Django 2.1.5 on 2019-02-09 01:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('especie', models.CharField(default='tilapia', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('tamaño_pez_cm', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tamaño pez cm')),
                ('peso_pez_gr', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('densidad_inicial', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('etapa', models.CharField(choices=[('siembra', 'siembra'), ('levante', 'levante'), ('engorde', 'engorde')], default='siembra', max_length=7)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('cosechado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cosecha', models.DateTimeField(blank=True, null=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estanque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_agua_mts', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('mts_2', models.PositiveSmallIntegerField(default=0, verbose_name='superficie_mts_2')),
                ('detalle', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='estanque',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.Finca'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='estanque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.Estanque'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.Finca'),
        ),
    ]
