# Generated by Django 2.1.5 on 2019-02-28 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='responsable',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estanque',
            name='finca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro.Finca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estanque',
            name='responsable',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estanque',
            name='tipo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
