# Generated by Django 2.1.1 on 2018-10-26 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina.Finca'),
        ),
        migrations.AddField(
            model_name='estanque',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina.Finca'),
        ),
    ]
