# Generated by Django 2.1.5 on 2019-03-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20190228_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='finca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro.Finca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
