# Generated by Django 2.1.1 on 2018-10-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20181025_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finca',
            old_name='admin',
            new_name='usuario',
        ),
    ]
