# Generated by Django 2.1.5 on 2019-03-20 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20190319_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estanque',
            name='mts_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
