# Generated by Django 2.1.5 on 2019-03-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20190319_2352'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cultivo',
            unique_together={('finca', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='estanque',
            unique_together={('finca', 'nombre')},
        ),
    ]
