# Generated by Django 2.1.1 on 2018-10-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20181025_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finca',
            old_name='usuario',
            new_name='usuarios',
        ),
    ]
