# Generated by Django 2.1.1 on 2018-10-26 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0006_auto_20181026_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='finca',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
