# Generated by Django 2.1.5 on 2019-03-20 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20190320_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='peso_pez_gr',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='tamaño_pez_cm',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
