# Generated by Django 2.1.5 on 2019-03-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20190320_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estanque',
            name='finca',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Finca'),
        ),
        migrations.AlterUniqueTogether(
            name='cultivo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='estanque',
            unique_together=set(),
        ),
    ]
