# Generated by Django 2.1.1 on 2018-10-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20181026_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='responsable',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000000003D926D8> <django.db.models.query_utils.DeferredAttribute object at 0x0000000003D92710>', max_length=100),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
