# Generated by Django 2.1.2 on 2018-10-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20181026_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='responsable',
            field=models.CharField(default='----', max_length=100),
        ),
    ]
