# Generated by Django 2.1.2 on 2018-11-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20181030_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='especie',
            field=models.CharField(default='tilapia', max_length=50),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='peso_gr',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tamaño_cm',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='estanque',
            name='mts_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estanque',
            name='nivel_agua_mts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='estanque',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
