# Generated by Django 2.1.2 on 2018-11-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_auto_20181101_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='usuarios',
        ),
    ]
