# Generated by Django 2.1.2 on 2018-11-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_remove_finca_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivo',
            old_name='fecha_siembra',
            new_name='fecha_registro',
        ),
        migrations.RenameField(
            model_name='cultivo',
            old_name='tamaño_cm',
            new_name='tamaño_pez_cm',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estanque',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estanque',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finca',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
