# Generated by Django 2.1.2 on 2018-11-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_auto_20181109_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivo',
            old_name='peso_gr',
            new_name='peso_pez_gr',
        ),
    ]
