# Generated by Django 2.1.2 on 2018-11-11 01:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_auto_20181109_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='estanque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.Estanque'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='tamaño_pez_cm',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='mts_2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='superficie_mts_2'),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='nivel_agua_mts',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
