# Generated by Django 2.1.2 on 2018-11-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_auto_20181110_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='cosechado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='densidad_inicial',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='etapa',
            field=models.CharField(choices=[('siembra', 'siembra'), ('levante', 'levante'), ('engorde', 'engorde')], default='siembra', max_length=7),
        ),
    ]
