# Generated by Django 2.1.2 on 2018-11-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_auto_20181117_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='fecha_cosecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
